name: mri_alignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - simpleitk=2.3.1
  - numpy=1.24.3
  - pillow=10.0.0
  - matplotlib
  - tk
  - pip
  - pip:
    - pyyaml  # For configuration file handling 